"""Planning Engine v1 domain boundary.

This package is intentionally independent from the legacy adaptive planner.
Only typed contracts live here until the new solver is implemented.
"""

from .content import plan_content_hash, semantic_plan_payload
from .models import (
    AggregateLoadEnvelope,
    ApprovedWorkoutOption,
    ContributionKind,
    CoverageRule,
    DailyAvailability,
    EligibilityKind,
    FixedLoadCommitment,
    LoadBound,
    LoadDimensionExposure,
    LoadDimensionLevel,
    LoadEstimate,
    LoadCompatibilityPolicy,
    LoadCompatibilityRule,
    ObligationContribution,
    ObservedLoadExposure,
    ObservedLoadSample,
    ObservedObligationCredit,
    OptionEligibility,
    PlanAuthorityState,
    PlanAuthorityStatus,
    PlanContent,
    PlannedTrainingWorkout,
    PlanningContractError,
    PlanningObligation,
    StrategyRevision,
    SameDayOrderRule,
    UnknownAggregatePolicy,
    WorkoutComponentIntent,
)

__all__ = [
    "AggregateLoadEnvelope",
    "ApprovedWorkoutOption",
    "ContributionKind",
    "CoverageRule",
    "DailyAvailability",
    "EligibilityKind",
    "FixedLoadCommitment",
    "LoadBound",
    "LoadDimensionExposure",
    "LoadDimensionLevel",
    "LoadEstimate",
    "LoadCompatibilityPolicy",
    "LoadCompatibilityRule",
    "ObligationContribution",
    "ObservedLoadExposure",
    "ObservedLoadSample",
    "ObservedObligationCredit",
    "OptionEligibility",
    "PlanAuthorityState",
    "PlanAuthorityStatus",
    "PlanContent",
    "PlannedTrainingWorkout",
    "PlanningContractError",
    "PlanningObligation",
    "StrategyRevision",
    "SameDayOrderRule",
    "UnknownAggregatePolicy",
    "WorkoutComponentIntent",
    "plan_content_hash",
    "semantic_plan_payload",
    "PlanValidationContext",
    "ValidationIssue",
    "ValidationReport",
    "validate_plan_content",
    "DoubleSessionPreference",
    "ObjectiveContext",
    "ObjectivePolicy",
    "ObjectiveVector",
    "SchedulePreferences",
    "SpacingPreference",
    "SpacingSubjectKind",
    "evaluate_objectives",
    "select_best_valid_plan",
]

from .validation import (
    PlanValidationContext,
    ValidationIssue,
    ValidationReport,
    validate_plan_content,
)

from .objectives import (
    DoubleSessionPreference,
    ObjectiveContext,
    ObjectivePolicy,
    ObjectiveVector,
    SchedulePreferences,
    SpacingPreference,
    SpacingSubjectKind,
    evaluate_objectives,
    select_best_valid_plan,
)
